name: Setup GitOps CLI
description: Download, install, and setup gitops cli to your path.
author: Max Partenfelder
branding:
  icon: play-circle
  color: white
inputs:
  version:
    description: 'The version of the gitops cli to install. (e.g. "latest", "1.2.3")'
    type: string
    required: false
  os:
    description: 'The operating system to install the gitops cli for. (e.g. "linux", "darwin", "windows")'
    type: string
    required: false
  arch:
    description: 'The architecture to install the gitops cli for. (e.g. "amd64", "arm64")'
    type: string
    required: false
  no-cache:
    required: false
    type: boolean
    default: false
    description: "Disable caching of bun executable."
outputs:
  gitops-cli-version:
    description: The version of the gitops cli that was installed.
  cache-hit:
    description: If the version of the gitops cli was cached.

runs:
  using: "node20"
  main: "dist/setup/index.js"
  # post: "dist/cache-save/index.js"
  # post-if: success()
